# Backstage Secrets
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
stringData:
  POSTGRES_USER: backstage
  POSTGRES_PASSWORD: backstage123
  GITEA_USERNAME: ""
  GITEA_PASSWORD: ""
