# Applications Cluster Configuration
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: app-cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 30000
        hostPort: 5000
        protocol: TCP
      - containerPort: 30001
        hostPort: 8081
        protocol: TCP
  - role: worker
  - role: worker
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.local:5000"]
      endpoint = ["http://registry.local:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gitea.local:3000"]
      endpoint = ["http://gitea.local:3000"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.local:5000".tls]
      insecure_skip_verify = true
    [plugins."io.containerd.grpc.v1.cri".registry.configs."localhost:5000".tls]
      insecure_skip_verify = true
