# Backstage Cluster Configuration
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: backstage-cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 7080
        protocol: TCP
      - containerPort: 443
        hostPort: 7443
        protocol: TCP
      - containerPort: 30007
        hostPort: 7007
        protocol: TCP
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.local:5000"]
      endpoint = ["http://registry.local:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.local:5000".tls]
      insecure_skip_verify = true
