# Gitea Actions 整合測試範例（手動觸發）
# 放置於 repository 的 .gitea/workflows/integration-test.yaml

name: Integration Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging

env:
  REGISTRY: localhost:5000

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      oracle:
        image: localhost:5000/oracle-xe:21-slim
        env:
          ORACLE_PASSWORD: test123
        ports:
          - 1521:1521
        options: >-
          --health-cmd "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/test123@localhost:1521/XEPDB1"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for Oracle to be ready
        run: |
          echo "Waiting for Oracle to be ready..."
          for i in $(seq 1 60); do
            if nc -z localhost 1521; then
              echo "Oracle is ready!"
              break
            fi
            echo "Waiting... ($i/60)"
            sleep 5
          done

      - name: Run database migrations
        run: |
          mvn flyway:migrate \
            -Dflyway.url=jdbc:oracle:thin:@localhost:1521/XEPDB1 \
            -Dflyway.user=system \
            -Dflyway.password=test123

      - name: Run integration tests
        run: mvn verify -Pintegration-test
        env:
          SPRING_DATASOURCE_URL: jdbc:oracle:thin:@localhost:1521/XEPDB1
          SPRING_DATASOURCE_USERNAME: system
          SPRING_DATASOURCE_PASSWORD: test123

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-reports
          path: |
            target/failsafe-reports/
            target/site/jacoco/
